name: build

on:
  push:
    branches: 
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      env:
        GHUSER: ${{ secrets.USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.DIGITAL_USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        debug: true
        script: |
          whoami
